# Generated by Django 5.0.8 on 2024-10-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='line_number',
            field=models.CharField(max_length=255),
        ),
    ]
