# Generated by Django 5.0.8 on 2024-10-07 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0002_alter_requestlog_line_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='log_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='requestlog',
            unique_together={('timestamp', 'url', 'user')},
        ),
    ]
